feat: init project
eggjs/egg-view-handlebars pull request #1
Opened 2017-02-27 07:41 UTC by huangyanxiong01

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2017-02-27 08:18 UTC, atian25 requested changes

2017-02-27 08:18 UTC, atian25 commented on app/extend/application.js
> +  get [Symbol.for('egg#view')]() {
这两个现在不需要了吧? @popomore 我们的那篇 VIEW 插件文档还没改完前, 是不是先屏蔽掉?

2017-02-27 08:18 UTC, atian25 commented on lib/view.js
> +function compile(tpl, context) {
为什么不作为 Handlebars 的成员方法?

2017-02-27 08:18 UTC, atian25 commented on lib/view.js
> +class Handlebars {
`HandlebarsView`

2017-02-27 08:18 UTC, atian25 commented on test/fixtures/apps/view-handlebars-test/config/config.default.js
> +	keys: 'e6099001cb0a0ec3eb8b0e1a54b27060',
缩进, 2 space

2017-02-27 10:08 UTC, huangyanxiong01 commented on lib/view.js
> +function compile(tpl, context) {
这个方法觉得应该是私有的，已经提供renderString，render的API，就没有必要将handlebars的核心方法暴露出去，用户知道越少越好(最少知识原则)

2017-02-27 10:12 UTC, huangyanxiong01 commented on lib/view.js
> +class Handlebars {
将classname改为HandlebarsView是吧！

2017-02-27 10:18 UTC, atian25 commented
私有的用 Symbol ，参考 egg 其他代码的写法

发自我的 iPhone

> 在 2017年2月27日，18:12，Freax <notifications@github.com> 写道：
> 
> @huangyanxiong01 commented on this pull request.
> 
> In lib/view.js:
> 
> > @@ -0,0 +1,28 @@
> +'use strict';
> +const fs = require('fs');
> +function compile(tpl, context) {
> +  return this.app.viewEngine.compile(tpl, this.app.config.view || {})(context);
> +}
> +class Handlebars {
> 将classname改为HandlebarsView是吧！
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-02-27 10:20 UTC, huangyanxiong01 commented on test/fixtures/apps/view-handlebars-test/config/config.default.js
> +	keys: 'e6099001cb0a0ec3eb8b0e1a54b27060',
如果我这么一改，会不会造成很多commit，之前贡献到docker项目的时候，会叫我压缩提交的，现在要不要先关闭这个合并请求，压缩后再提交

2017-02-27 10:22 UTC, popomore commented on lib/view.js
> +function compile(tpl, context) {
挂在 view 上呗

2017-02-27 10:23 UTC, popomore commented on app/extend/application.js
> +  get viewEngine() {
这个不用写了，直接在 view 上调 handlebars 就好了

2017-02-27 10:24 UTC, popomore commented
缺少默认配置，文档

2017-03-02 07:02 UTC, huangyanxiong01 commented
@atian25 关于Codecov Report未通过的问题，我需要了解什么吗

2017-03-02 07:07 UTC, popomore commented
不用，第一次都这样

2017-03-02 07:08 UTC, popomore commented on README.zh_CN.md
> +	view: {
详细配置就加个链接吧，把一些常用的在上面的文档说明下如何使用。

2017-03-02 07:09 UTC, popomore commented on README.md
> +		data:false,
这个 data 是什么

2017-03-02 07:09 UTC, popomore commented on config/config.default.js
> + * @property [data=boolean] set to false to disable data tracking.
类型是 `{Boolean}`，`=` 后面是默认值

2017-03-02 07:11 UTC, popomore commented on app.js
> +      return handlebars.compile(tpl, Object.assign(this.app.config.handlebars, this.app.config.view) || {})(context);
这里不需要读取 this.app.config.view 的配置吧？

2017-03-02 07:12 UTC, popomore commented on app.js
> +      return handlebars.compile(tpl, Object.assign(this.app.config.handlebars, this.app.config.view) || {})(context);
render 支持 `render(name, ctx, options)`，最好合并调用的 options，这样可以在调用时覆盖默认参数。

2017-03-02 07:12 UTC, popomore commented on app.js
> +      return new Promise(resolve => {
同步写法可以改成 `Promise.resolve(this[COMPILE](tpl, context))`

2017-03-02 07:13 UTC, popomore commented on app.js
> +      return new Promise(resolve => {
这里要加个 try/catch，加个错误的模板试试是否报错

2017-03-02 07:16 UTC, huangyanxiong01 commented on app.js
> +      return handlebars.compile(tpl, Object.assign(this.app.config.handlebars, this.app.config.view) || {})(context);
用户自定义配置不是放在view么，需要覆盖默认配置的

2017-03-02 07:17 UTC, huangyanxiong01 commented on app.js
> +      return new Promise(resolve => {
谢谢，指正

2017-03-02 07:17 UTC, huangyanxiong01 commented on README.md
> +		data:false,
用户自定义的配置

2017-03-02 08:02 UTC, popomore commented on app.js
> +      return handlebars.compile(tpl, Object.assign(this.app.config.handlebars, this.app.config.view) || {})(context);
不是的，你的配置定义在 config.handlebars，那开发者也是配这个。

2017-03-03 13:21 UTC, huangyanxiong01 commented on app.js
> +      return new Promise(resolve => {
模板的错误框架会捕获，没有必要再 try/catch了

2017-03-03 13:24 UTC, popomore commented on app.js
> +      return new Promise(resolve => {
如果是在 promise 没有 reject 会有问题吧，这里同步执行还好，加个用例吧

2017-03-06 14:39 UTC, atian25 commented
is there anything block this PR?

2017-03-06 15:07 UTC, popomore commented on README.zh_CN.md
> +请到 [egg issues](https://github.com/eggjs/egg/issues) 移步交流。
这

2017-03-06 15:08 UTC, popomore commented on config/config.default.js
> + * @property [data=boolean] set to false to disable data tracking.
这里没改

2017-03-06 15:09 UTC, popomore approved these changes
可以先合并

2017-03-08 04:26 UTC, merged

2017-03-08 04:27 UTC, popomore commented
感谢 @huangyanxiong01 的工作

2017-03-08 04:47 UTC, atian25 commented
发版本了么?

2017-03-08 04:49 UTC, atian25 commented
```bash
$ npm owner ls egg-view-handlebars
huangyanxiong <huangyanxiong2013@gmail.com>
```

@huangyanxiong01 麻烦给我们加下 owner，发下版本：

```bash
$ npm owner add eggjs egg-view-handlebars
$ npm owner add fengmk2 egg-view-handlebars
$  npm owner add popomore egg-view-handlebars
$ npm owner add dead_horse egg-view-handlebars
$ npm owner add atian25 egg-view-handlebars
```

2017-03-08 05:07 UTC, popomore commented
有 bug https://github.com/eggjs/egg-view-handlebars/pull/2

2017-03-09 04:03 UTC, huangyanxiong01 commented
@atian25 给了