feat: support handlebars partials
eggjs/egg-view-handlebars pull request #3
Opened 2017-03-29 10:15 UTC by popomore

Closes https://github.com/eggjs/egg/issues/604

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2017-03-29 10:18 UTC, atian25 commented on README.md
> +    userMessage: '<{{tagName}}>By {{author.firstName}} {{author.lastName}}</{{tagName}}>'
- 放在 config 有点小恶心, 放到 app/view/partial ?
- partials or partial ?
- 不过文件加载他们自己搞也行

2017-03-29 10:23 UTC, popomore commented on README.md
> +    userMessage: '<{{tagName}}>By {{author.firstName}} {{author.lastName}}</{{tagName}}>'
还好吧，可以自己 require，

2017-03-29 10:23 UTC, popomore commented on README.md
> +    userMessage: '<{{tagName}}>By {{author.firstName}} {{author.lastName}}</{{tagName}}>'
不喜欢文件，不然又有大小写驼峰问题

2017-03-29 10:27 UTC, popomore commented on README.md
> +    userMessage: '<{{tagName}}>By {{author.firstName}} {{author.lastName}}</{{tagName}}>'
好像是这个意思，那我改改 https://github.com/koajs/koa-hbs#registering-partials

2017-03-30 02:35 UTC, atian25 commented on app.js
> +  const files = fs.readdirSync(partialsPath);
突然感觉有点 `loader.loadFile()` 或者说一个 utils 类的场景，加载一个文件，默认的 extensions 是 js 处理，支持自定义处理，如 tpl，如 yml，如 json 之类的。

2017-03-30 02:42 UTC, popomore commented
@atian25 看看

2017-03-30 02:48 UTC, popomore commented on app.js
> +  const files = fs.readdirSync(partialsPath);
恩，可以优化下

2017-03-30 02:53 UTC, atian25 requested changes

2017-03-30 02:53 UTC, atian25 commented on app.js
> +      .replace(/\.\w+$/, '')
这是去掉后缀名? `a.hbs.tpl` 这种情况有问题.

2017-03-30 02:53 UTC, atian25 commented on README.md
> +Partials are loaded from `app/view/partials` by default, you can define `user_message.hbs` and use `userMessage` as partial.
- koa-partials 那边也不支持多级吧? 文档注明下我们不支持多级.
- 单复数 partials 还是 partial ?

2017-03-30 02:53 UTC, atian25 commented on app.js
> +  const files = fs.readdirSync(partialsPath);
读文件这里感觉有共性，是不是抽象到 `loader.loadFile` 去

2017-03-30 02:56 UTC, popomore commented on app.js
> +      .replace(/\.\w+$/, '')
一般都是根据 mapping 后缀写吧

2017-03-30 02:57 UTC, popomore commented on app.js
> +  const files = fs.readdirSync(partialsPath);
晚点改，没想好怎么改

2017-03-30 02:59 UTC, atian25 commented on app.js
> +      .replace(/\.\w+$/, '')
可以用 `name.split('.')[0]`

2017-03-30 05:25 UTC, popomore commented on README.md
> +Partials are loaded from `app/view/partials` by default, you can define `user_message.hbs` and use `userMessage` as partial.
拷贝的 partialsPath，默认是 partials

2017-03-30 14:29 UTC, popomore commented
可以合了吗

2017-03-30 14:30 UTC, popomore commented on app.js
> +      .replace(/\.\w+$/, '')
这样不准确，用 replace 有什么问题吗

2017-03-30 14:36 UTC, atian25 commented on app.js
> +      .replace(/\.\w+$/, '')
以为还要改这个. 可以合了.

如果是 `user_list.hbs.tpl` 的情况, 最终的 partial name 是 `userList.hbs` 了吧?
如果是 split 则是 `userList`

2017-03-30 14:37 UTC, atian25 approved these changes

2017-03-30 14:55 UTC, popomore commented on app.js
> +      .replace(/\.\w+$/, '')
但是为什么这么写呢

2017-03-30 15:04 UTC, atian25 commented on app.js
> +      .replace(/\.\w+$/, '')
之前看过 UC 那边有这类的模板命名方式... 先不管了，遇到反馈再说。合了吧

2017-03-30 15:05 UTC, merged

2017-03-30 15:06 UTC, atian25 commented
你发版本吧

2017-03-31 09:46 UTC, popomore commented
+ egg-view-handlebars@1.2.0