feat: support handlebars layout
eggjs/egg-view-handlebars pull request #6
Opened 2017-11-27 04:37 UTC by sinchang

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

support handlebars layout

2017-12-11 08:35 UTC, atian25 commented on app.js
> +      if (fs.existsSync(layoutsPath)) {
`await fs.exist()`

2017-12-11 08:35 UTC, atian25 commented on app.js
> +        const layoutContent = fs.readFileSync(`${layoutsPath}/${layout}.hbs`).toString();
`const layoutContent = await fs.readFile(path.join(layoutsPath, `${layout}.hbs`), 'utf-8');`

2017-12-11 08:55 UTC, atian25 approved these changes
@popomore 看看

2018-03-05 05:57 UTC, popomore requested changes

2018-03-05 05:57 UTC, popomore commented on app.js
> +      const isExistLayoutsPath = await fs.exists(layoutsPath);
这个检查可以放到 app.js 里面去做，不然每次渲染都要做。

2018-03-05 05:57 UTC, popomore commented on app.js
> +      let layout = context.layout;
这个参数最好从 options 读

2018-03-05 05:57 UTC, popomore commented on app.js
> +        const layoutContent = await fs.readFile(path.join(layoutsPath,`${layout}.hbs`), 'utf-8');
加个读文件缓存

2018-08-15 14:48 UTC, closed without merging